name: movie_app
description: Movie app with exact UI (dark + yellow) + localization + avatar picker

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  easy_localization: ^3.0.1
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/